### PR TITLE
Make the build work in CoreOS with systemd-nspawn

### PR DESCRIPTION
**Pull request by larstobi**
sudo systemd-nspawn --bind=/lib/modules --image=coreos_developer_container.bin
https://coreos.com/os/docs/latest/kernel-modules.html#prepare-a-coreos-container-linux-development-container

### CODE REVIEW

**Comment by lorenz** [comment]
Thanks! I'll verify this on my CI to see if there are any regressions. Could you also add the new build method to the README?

**Review by lorenz — APPROVED** [review]
I just ran these though CI, still builds fine

**Comment by larstobi** [comment]
I tried to boot the resulting module, and it has the kernel version in the path, and then insmod can't find the ko, so I have removed the path in the script. WIll update the patch soon.

**Comment by larstobi** [comment]
I have switched to the flatcar-linux variant of coreos to get more bleeding-edge versions of the software using their edge group. I've made changes to the way I do this, so I'll close this PR and make a new one later.

**Pull request closed without merging**
